#!/usr/bin/env bash
# ============================================================================
# RunPod 컨테이너 엔트리포인트
#  - PUBLIC_KEY(RunPod이 주입) 로 SSH 공개키 등록
#  - 컨테이너 ENV를 SSH 세션에도 전달 (RunPod에서 가장 흔한 함정)
#  - /workspace 캐시 디렉터리 준비
# ============================================================================
set -euo pipefail

echo "[start] $(date -Is) booting vmax-runpod container"

# ---------------------------------------------------------------------------
# 1. 캐시/작업 디렉터리 (네트워크 볼륨이 마운트된 뒤에 생성해야 함)
# ---------------------------------------------------------------------------
mkdir -p /workspace/.cache/{uv,huggingface,jax} \
         /workspace/data \
         /workspace/runs

# ---------------------------------------------------------------------------
# 2. 컨테이너 ENV를 SSH 세션에 전달
#    sshd 세션은 Docker ENV를 상속하지 않는다. 이걸 안 해두면 SSH로 들어왔을 때
#    PATH에 /opt/venv/bin이 없어서 "python: command not found"를 보게 된다.
# ---------------------------------------------------------------------------
{
  echo "# generated by start.sh - do not edit"
  printenv | grep -Ev '^(PWD|SHLVL|_|OLDPWD|HOME|USER|LOGNAME|SSH_|TERM)=' \
    | while IFS='=' read -r k v; do
        printf 'export %s=%q\n' "$k" "$v"
      done
} > /etc/profile.d/00-runpod-env.sh
chmod 644 /etc/profile.d/00-runpod-env.sh

# 비로그인 셸(VSCode Remote 등)도 커버
if ! grep -q '00-runpod-env.sh' /root/.bashrc 2>/dev/null; then
  echo '[ -f /etc/profile.d/00-runpod-env.sh ] && . /etc/profile.d/00-runpod-env.sh' >> /root/.bashrc
fi

# ---------------------------------------------------------------------------
# 3. SSH
# ---------------------------------------------------------------------------
if [[ -n "${PUBLIC_KEY:-}" ]]; then
  mkdir -p /root/.ssh
  chmod 700 /root/.ssh
  # 재시작 시 중복 등록 방지
  touch /root/.ssh/authorized_keys
  grep -qxF "$PUBLIC_KEY" /root/.ssh/authorized_keys || echo "$PUBLIC_KEY" >> /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
  echo "[start] PUBLIC_KEY registered"
else
  echo "[start] WARNING: PUBLIC_KEY is empty - SSH 키 로그인 불가."
  echo "[start]          RunPod 콘솔의 Settings > SSH Public Keys 에 키를 등록하세요."
fi

ssh-keygen -A >/dev/null 2>&1 || true
mkdir -p /run/sshd
/usr/sbin/sshd -D -e &
echo "[start] sshd listening on 22"

# ---------------------------------------------------------------------------
# 4. 워크스페이스 부트스트랩 (최초 1회, V-Max 클론 + editable 설치)
#    AUTO_BOOTSTRAP=0 으로 끌 수 있음
# ---------------------------------------------------------------------------
if [[ "${AUTO_BOOTSTRAP:-1}" == "1" ]]; then
  /usr/local/bin/bootstrap-workspace.sh || echo "[start] bootstrap 실패 - 수동으로 bootstrap-workspace.sh 실행하세요"
fi

echo "[start] ready. 'ssh root@<POD_IP> -p <PORT> -i ~/.ssh/id_ed25519' 로 접속하세요."

# ---------------------------------------------------------------------------
# 5. 컨테이너 유지
# ---------------------------------------------------------------------------
exec sleep infinity
